language: bash

dist: bionic

env:
  - CI_NAME=travis DOCKER_CLI_EXPERIMENTAL=enabled rebuild="failed" imageName="socat"

before_install:
  - sudo rm -rf /var/lib/apt/lists/*
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - lsb_release -cs
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - sudo service docker restart
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
  - docker version
  - bash ./build.sh ${rebuild}
  - docker run -ti --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/.cache:/root/.cache aquasec/trivy image --severity HIGH,CRITICAL alpine/${imageName}
